language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
# Use sdist and pip install to test a distribution tarball
install: "python setup.py sdist; find ./dist/ -iname *.tar.gz | xargs pip install"
# command to run tests
script: py.test tests
